###
GET {{server}}/hello/str?name=ryan
Accept: text/plain

###
POST {{server}}/hello/str
Accept: text/plain
Content-Type: application/x-www-form-urlencoded

name=ryan

###
POST {{server}}/hello/user
Accept: application/json
Content-Type: application/json

{"name":"ryan","age":18}

###
GET {{server}}/crypto/str?name=ryan
Accept: application/json

###
POST {{server}}/crypto/str
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=ryan

###
POST {{server}}/crypto/user
Accept: application/json
Content-Type: application/json

{"name":"ryan","age":18}

###
POST {{server}}/crypto/encrypt/str
Accept: application/json
Content-Type: application/json

{
  "encrypt": "1e1FaIpuOAyTAWDp91vzYQ==",
  "sign": "64faa4f5e336da5d80aa8fcc90593a13",
  "ts": 1606814829990,
  "nc": "VksTUj"
}

###
POST {{server}}/crypto/encrypt/user
Accept: application/json
Content-Type: application/json

{
  "encrypt": "nQm15OAj01ZT/MtBuZkr/cFDODJ6z00ipKh9sxiKEnc=",
  "sign": "f941c698678a612a2e338c526fe68227",
  "ts": 1606814687635,
  "nc": "QTZ3va"
}

###
